# Generated by Django 2.2.1 on 2019-09-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190913_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='image_url',
            field=models.URLField(default='/static/accounts/default.png'),
        ),
    ]
