# Generated by Django 2.2.1 on 2019-09-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20190915_1628'),
        ('users', '0003_siteuser_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
