# Generated by Django 2.2.1 on 2020-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190915_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
