# Generated by Django 2.2.1 on 2020-03-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20190915_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='views',
        ),
    ]
