# Generated by Django 2.2.1 on 2020-03-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20190915_1628'),
        ('user_manga_integration', '0003_userchapterbookmarkentry_is_manually_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchapterbookmarkentry',
            name='chapter_number',
        ),
        migrations.AddField(
            model_name='userchapterbookmarkentry',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manga.Chapter'),
            preserve_default=False,
        ),
    ]
