# Generated by Django 2.2.1 on 2020-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manga_integration', '0004_auto_20200312_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapterbookmarkentry',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermangarating',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermangawatchlistentry',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertagssubscriptionentry',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertagssubscriptionentrytag',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
