# Generated by Django 2.2.1 on 2020-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manga_integration', '0005_auto_20200312_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapterbookmarkentry',
            name='accessed_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
