# Generated by Django 2.2.1 on 2020-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manga_integration', '0006_userchapterbookmarkentry_accessed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchapterbookmarkentry',
            name='accessed_on',
            field=models.DateTimeField(),
        ),
    ]
