# Generated by Django 2.2.1 on 2020-03-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manga_integration', '0007_auto_20200313_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchapterbookmarkentry',
            name='accessed_on',
        ),
    ]
