# Generated by Django 2.2.1 on 2020-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manga_integration', '0008_remove_userchapterbookmarkentry_accessed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermangarating',
            name='rating_value',
            field=models.FloatField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
