# Generated by Django 2.2.1 on 2020-03-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manga_integration', '0009_auto_20200314_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermangarating',
            old_name='rating_value',
            new_name='rating',
        ),
    ]
