# Generated by Django 2.2.7 on 2020-04-15 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_remove_chapter_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_manga_integration', '0012_auto_20200315_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapterHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.Chapter')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.Manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
