# Generated by Django 2.2.7 on 2020-08-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga', '0003_remove_chapter_views'),
        ('user_manga_integration', '0013_userchapterhistoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMangaReadingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_mode', models.CharField(choices=[['SINGLE_PAGE', 'SINGLE_PAGE'], ['WEB_TOON', 'WEB_TOON']], max_length=12)),
                ('theme', models.CharField(choices=[['DEFAULT', 'DEFAULT']], max_length=12)),
                ('manga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manga.Manga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
