# Generated by Django 2.2.7 on 2020-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
